export const enum RouteConstants {
	SplashScreenRoute = 'SPLASH_SCREEN',
	HomeScreenRoute = 'HOME_SCREEN',
	PermissionsScreenRoute = 'PERMISSIONS_SCREEN',
	TabsScreenRoute = 'TABS_SCREEN',
	MainWebviewScreenRoute = 'MAIN_WEBVIEW_SCREEN_ROUTE',
	LoginRoute = 'LOGIN_SCREEN',
	SignUpRoute = 'SIGN_UP_SCREEN',
	OtpRoute = 'OTP_SCREEN',
	ProductdeatilsScreenRoute = 'PRODUCT_DETAILS_ROUTE',
	StoreScreenRoute = 'STORE_SCREEN',
	CategoriesScreenRoute = 'CATEGORIES_SCREEN_ROUTE',
	ViewMoreSimilarProductScreenRoute = 'VIEW_MORE_SIMILAR_PRODUCT_SCREEN_ROUTE',
	LocationScreenRoute = 'LOCATION_SCREEN_ROUTE',
	PincodeScreenRoute = 'PINCODE_SCREEN_ROUTE',
	CartScreenRoute = 'CART_SCREEN_ROUTE',
	UserAccountScreenRoute = 'USER_ACCOUNT_SCREEN_ROUTE',
	MyProfileScreenRoute = 'MY_PROFILE_SCREEN_ROUTE',
	CustomerSupportScreen = 'CUSTOMER_SUPPORT_SCREEEN'
}
