export const LOCAL_STORAGE_KEYS = {
	ACCESS_TOKEN: 'ACCESS_TOKEN',
	REFRESH_TOKEN: 'REFRESH_TOKEN',
	LATITUDE: 'latitude',
	LONGITUDE: 'longitude',
	USER_LOCATION: 'USER_LOCATION',
	SHOW_LOCATION_MODAL: 'SHOW_LOCATION_MODAL',
	CART_TYPE: 'CART_TYPE'
} as const;
